# Generated by Django 5.2 on 2025-05-01 10:37

import PulseCampus.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classes', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, validators=[PulseCampus.validators.no_digit])),
                ('student_id', models.CharField(max_length=10, validators=[PulseCampus.validators.id_validate])),
                ('address', models.TextField(max_length=500)),
                ('is_captain', models.BooleanField(default=False)),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, validators=[PulseCampus.validators.no_digit])),
                ('joining_date', models.DateField(validators=[PulseCampus.validators.no_future_date])),
                ('address', models.TextField(max_length=500)),
                ('designation', models.CharField(max_length=100, validators=[PulseCampus.validators.no_digit])),
                ('dept_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
        ),
    ]
