# Generated by Django 4.2.11 on 2025-05-02 06:21

import PulseCampus.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, validators=[PulseCampus.validators.no_digit])),
                ('designation', models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal')], max_length=100)),
                ('joining_date', models.DateField(validators=[PulseCampus.validators.no_future_date])),
                ('address', models.TextField(max_length=500)),
                ('room_number', models.CharField(max_length=4, validators=[PulseCampus.validators.all_digits])),
                ('building_number', models.CharField(max_length=4, validators=[PulseCampus.validators.all_digits])),
            ],
        ),
    ]
