# Generated by Django 5.2 on 2025-05-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
