# Generated by Django 4.2.11 on 2025-05-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
