# Generated by Django 5.2 on 2025-05-17 12:00

import PulseCampus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='building_number',
            field=models.CharField(max_length=2, validators=[PulseCampus.validators.all_digits]),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_number',
            field=models.CharField(max_length=3, validators=[PulseCampus.validators.all_digits]),
        ),
    ]
