# Generated by Django 5.2 on 2025-05-17 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
