# Generated by Django 5.2 on 2025-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_class_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('class_code', '')), name='class code can not be empty'),
        ),
    ]
