# Generated by Django 5.2 on 2025-05-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_class_code_can_not_be_empty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='class code can not be empty',
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('class_code', ''), _negated=True), name='class code can not be empty'),
        ),
    ]
