# Generated by Django 5.2 on 2025-05-26 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_post_vote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
