# Generated by Django 5.2 on 2025-05-14 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
