# Generated by Django 5.2 on 2025-05-26 07:28

import PulseCampus.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(['pdf']), PulseCampus.validators.file_less_than_2mb]),
        ),
    ]
