# Generated by Django 5.2 on 2025-05-03 04:15

import PulseCampus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('room_number', models.CharField(max_length=4, validators=[PulseCampus.validators.all_digits])),
                ('building_number', models.CharField(max_length=4, validators=[PulseCampus.validators.all_digits])),
            ],
        ),
    ]
