# Generated by Django 5.2 on 2025-05-01 10:37

import PulseCampus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=4, validators=[PulseCampus.validators.all_digits])),
                ('building_number', models.CharField(max_length=4, validators=[PulseCampus.validators.all_digits])),
            ],
        ),
    ]
